# Generated by Django on 2026-09-16
import django.core.validators
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, help_text='Unique identification code (e.g. EMP001)', max_length=20, unique=True)),
                ('full_name', models.CharField(help_text="Employee's full legal name", max_length=100)),
                ('email', models.EmailField(db_index=True, help_text='Unique corporate or personal email address', max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Primary contact phone number', max_length=20)),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('Human Resources', 'Human Resources'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Design', 'Design'), ('Operations', 'Operations')], default='Engineering', help_text='Assigned company department', max_length=50)),
                ('designation', models.CharField(help_text='Job title/designation within the company', max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, help_text='Monthly or annual compensation in currency units (must be > 0)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date_of_joining', models.DateField(help_text='Official joining date')),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Intern', 'Intern')], default='Full-time', help_text='Contract type: Full-time, Part-time, or Intern', max_length=20)),
                ('address', models.TextField(blank=True, default='', help_text='Residential postal address')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Current employment status (Active or Inactive)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created in the database')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
            },
        ),
    ]
